### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by HeisenbergCipherCracker** [HeisenbergCipherCracker/sqlgo#4]
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'tuple' object is not callable

**Comment by Zackieeee** [comment]
Hi， there seem to be issued with your function as stated in the traceback line ( *self._args, **self._kwargs ) which involves function argument ( the codes you need to insert into the bracket for the function to work, Exp: func() , ) and ** arbitrary keyword argument which you may seem to be working with a tuple . 

However **do take note of the python collection type ( set , list , tuple and dict ) They work very differently**  . It will help more if you note which appropriate collection type to choose from , else you can show what code you are working on so I can further analysis the issues . Thanks!

![python-list-tuple-set-array-dict-6-1024x543](https://github.com/HeisenbergCipherCracker/sqlgo/assets/157857181/a63d3852-c313-4c0e-b659-a58a33530730)

**Comment by joaomarcosjova** [comment]
The error message indicates that there is a `TypeError` occurring in your Python code related to threading. Specifically, the error is caused by attempting to call a tuple object, which is not callable.

Here are some steps you can take to diagnose and resolve the issue:

1. **Check the Threading Code**: Review the threading code in your Python script to identify where the issue is occurring. The error message indicates that the problem lies within the `run()` method of a thread.

2. **Review the Target Function**: In Python's threading module, you typically specify a target function that the thread will execute. Ensure that the target function you provided is callable and does not inadvertently reference a tuple object.

3. **Check Arguments and Keyword Arguments**: The `TypeError` could also be caused by incorrect arguments or keyword arguments passed to the target function. Make sure that the arguments and keyword arguments match the function's signature.

4. **Inspect Imported Modules**: If your target function relies on imported modules or external code, ensure that those modules are imported correctly and that their functions and objects are used appropriately.

5. **Review Thread Creation**: Double-check how you create and start threads in your Python script. Ensure that you are passing the correct arguments and that the target function is properly specified.

6. **Handle Exceptions**: Wrap the code within the target function with a try-except block to catch any exceptions that may occur during execution. This can help identify specific errors and provide more context for debugging.

Once you have identified the specific line or section of code causing the issue, you can make the necessary corrections to resolve the `TypeError`. If you need further assistance, please provide the relevant code snippet, and I'd be happy to help further.

**Comment by HeisenbergCipherCracker** [comment]
Thanks, The issue has been resolved!
